#!/bin/bash

#   This file echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).
#

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
bld=$'\e[1m'
rst=$'\e[0m'

cat << EOF

 $f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst
 $f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst
 $f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst
 $f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst

 $bld$f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst
 $bld$f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst
 $bld$f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst
 $bld$f0████████  $f1████████  $f2████████  $f3████████  $f4████████  $f5████████  $f6████████  $f7████████$rst

EOF
